### PR TITLE
Update images and favicons on website to new logo.

### PR DESCRIPTION
**Pull request by josephfusco**
See logo update PR in [https://github.com/SelfControlApp/selfcontrol/pull/320](https://github.com/SelfControlApp/selfcontrol/pull/320)

### CODE REVIEW

**Comment by josephfusco** [comment]
screen shot 2015-12-31 at 1 06 19 am

**Comment by cstigler** [comment]
:+1:

**Comment by cstigler** [comment]
@josephfusco cool if we credit you on the website? we can link to your Twitter, GitHub, whatever you prefer

**Comment by josephfusco** [comment]
GitHub is cool. thanks :)

**Comment by cstigler** [comment]
great, done!

**Comment by slambert** [comment]
So, when is this release happening?

**Comment by josephfusco** [comment]
:point_up: :spades: :skull:

**Comment by cstigler** [comment]
Hopefully tomorrow... Apple has been giving me trouble with the developer account that we use for code signing, but I think it's resolved now after some conversation with the folks there.

**Comment by slambert** [comment]
Just a casual conversation with the folks at Apple... no biggie...

**Comment by cstigler** [comment]
The update is out now!

**Pull request merged**
